services:
  mc-manager:
    build: .

    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - ./data:/data
      - ./logs:/logs

      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock