# Generated by Django 6.0.6 on 2026-07-16 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mc_version', models.CharField(max_length=20, verbose_name='Minecraft Version')),
                ('mod_loader', models.CharField(choices=[('vanilla', 'Vanilla'), ('forge', 'Forge'), ('fabric', 'Fabric'), ('paper', 'Paper'), ('neoforge', 'NeoForge'), ('quilt', 'Quilt'), ('purpur', 'Purpur'), ('spigot', 'Spigot'), ('bukkit', 'Bukkit')], default='vanilla', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('server_path', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('starting', 'Starting'), ('stopping', 'Stopping'), ('error', 'Error')], default='created', max_length=20)),
                ('port', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
