# Generated by Django 6.0 on 2026-07-16 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_APP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='memory_gb',
            field=models.PositiveIntegerField(default=2, help_text='RAM limit for the Minecraft server container in gigabytes.', verbose_name='Memory (GB)'),
        ),
        migrations.CreateModel(
            name='ServerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_granted_by', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core_APP.minecraftserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['granted_at'],
                'unique_together': {('server', 'user')},
            },
        ),
    ]
